SOCIAL_TITLE_MR_RADIO = "input[name='id_gender'][value='1']"
SOCIAL_TITLE_MRS_RADIO = "input[name='id_gender'][value='2']"
FIRSTNAME_INPUT = "firstname"
LASTNAME_INPUT = "lastname"
BIRTHDAY_INPUT = "birthday"
RECEIVE_OFFERS_CHECK = "optin"
NEWSLETTER_CHECK = "newsletter"
TERMS_AND_PRIVACY_CHECK = "psgdpr"
SAVE_BUTTON = "//button[@data-link-action='save-customer']"
ERROR_MESSAGE = "div.help-block ul li.alert.alert-danger"
